apiVersion: apps/v1
kind: Deployment
metadata:
  name: wavefront-proxy
spec:
  template:
    spec:
      containers:
        - name: wavefront-proxy
          env:
            - name: JAVA_HEAP_USAGE
              valueFrom:
                configMapKeyRef:
                  name: wavefront-proxy-heap-size
                  key: JAVA_HEAP_USAGE
          resources:
          limits:
            memory: "2Gi"