apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- wavefront.yaml

configMapGenerator:
- name: wavefront-config
  files:
    - configs/wavefront.conf
    - configs/log4j2.xml
- name: wavefront-env
  literals:
  - WAVEFRONT_URL=https://try.wavefront.com/api/

secretGenerator:
- name: wavefront-token
  literals:
  - WAVEFRONT_TOKEN=

patches:
- path: wavefront-proxy-config-patch.yaml
  target:
    kind: Deployment
