name: CI

on: [push, pull_request]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Kubernetes tools
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.0
          kustomize: 3.4.0
          helm: 2.16.5
          helmv3: 3.1.2
          command: |
            echo "Run conftest"
            kustomize build base/ | conftest test -p test/policy -
            echo "Run kubeval"
            kustomize build base/ | kubeval --strict
